### ISSUE TITLE
Using of symfony/messenger

### ISSUE THREAD

**Issue by karousn** [simPod/KafkaBundle#10]
Have any plan to use [symfony/messenger](https://symfony.com/doc/current/components/messenger.html) for send/recieve message as an abstract ?

**Comment by simPod** [comment]
Hi @karousn, probably not, I don't see any value that it would have added this bundle. The API here is pretty much open so anyone is free to implement that messenger in their application. Or am I missing something?  
Thanks for issue

**Comment by simPod** [comment]
I'll base the bundle on https://github.com/simPod/Kafka
