### ISSUE TITLE
Please add tags

### ISSUE THREAD

**Issue by JordyMoos** [simPod/KafkaBundle#12]
Can you please create tags so its easier to pick a build?

I would like to have a stable version for php 7.1 but your master forces my hand to 7.2.
Adding tags could fix that

**Comment by simPod** [comment]
@JordyMoos still valid requirement? The issue is closed

**Comment by JordyMoos** [comment]
Hi @simPod, your bundle only focusses on symfony 4 while I'm at symfony 3 therefor I can not use this bundle

**Comment by simPod** [comment]
@JordyMoos Hi, I decided not to bother with Symfony <4. Currently, the support is for 4.3+, I'm willing to merge PR adding support for anything ^4.0.
